minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - npm-plugin-kit

trustPolicy: no-downgrade
trustPolicyExclude:
  - why-is-node-running

shellEmulator: true

packages:
  - packages/*

allowBuilds:
  esbuild: true
  simple-git-hooks: true
